### ISSUE TITLE
Config Error: File contains no section headers

### ISSUE THREAD

**Issue by salipro4ever** [supermasita/ufe#2]
I get this error after run cmd: ` yum --enablerepo=atrpms* install ffmpeg`
```
Loaded plugins: fastestmirror, security
Config Error: File contains no section headers.
file: file://///etc/yum.repos.d/atrpms.repo, line: 1
'me=Fedora Core 5 - x86_64 - ATrpms\n'
```

**Comment by supermasita** [comment]
Sorry for the late answer. If its still useful, I think the best way is to install Kaltura's FFMPEG; AtRpms has many problems and compiling is daunting...

U could install the rpm :
```
rpm -ihv http://installrepo.kaltura.org/releases/kaltura-release.noarch.rpm
```

FFMPEG:
```
yum install ffmpeg
```

And u ll find the binary in "/opt/kaltura/bin/ffmpeg". You can make a symbolic link:
```
ln -s /opt/kaltura/bin/ffmpeg /usr/bin/
```

I ll update the documentation soon. I ll also be updating the code.

**Comment by salipro4ever** [comment]
thanks!

**Comment by supermasita** [comment]
New version includes Dockerfile to easily create a container with FFMPEG compiled - Im also working on Docker Hub automated builds.

Cheers!
